sudo: required
language: generic
services:
  - docker

env:
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO=kinetic ROS_REPO=ros OS_NAME=debian OS_CODE_NAME=jessie
    - ROS_DISTRO=lunar   ROS_REPO=ros
    - ROS_DISTRO=lunar   ROS_REPO=ros-shadow-fixed

install: git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config
script: .ci_config/travis.sh
